FROM ubuntu:16.04

LABEL Description="This image is used to start SequoiaDB"
LABEL Vendor="SequoiaDB Ltd."
LABEL Version="5.01"
LABEL Maintainer="contact@sequoiadb.com"

ARG workdir=/home/shiyanlou


#USER root

WORKDIR $workdir

ADD sources.list ./
RUN mv sources.list /etc/apt/


RUN apt-get -y update \
    && apt-get -y install sudo \
    && apt-get -y install vim \
    && apt-get -y install net-tools

# add CHINA
RUN apt-get -y install language-pack-zh-hans
RUN apt-get install -y tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
ENV LANG="zh_CN.UTF-8"
RUN echo "export LC_ALL=zh_CN.UTF-8"  >>  /etc/profile &&  echo "export LC_ALL=zh_CN.UTF-8" >>/root/.bashrc
RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8

# add shiyanlou user 
RUN useradd shiyanlou \
    && echo 'shiyanlou:shiyanlou' |chpasswd \
    && usermod -s /bin/bash shiyanlou

RUN cat /etc/hosts


ADD sequoiadb-5.0.1-enterprise-linux_x86_64.tar.gz ./


RUN chmod +x $workdir/sequoiadb-5.0.1/sequoiadb-5.0.1-linux_x86_64-enterprise-installer.run

RUN $workdir/sequoiadb-5.0.1/sequoiadb-5.0.1-linux_x86_64-enterprise-installer.run  --installer-language zh_CN --prefix /opt/sequoiadb  --username sdbadmin --groupname  sdbadmin_group --userpasswd sdbadmin --unattendedmodeui none  --SMS false --processAutoStart false --port 11790 --mode  unattended \
; exit 0
RUN echo 'export TERMINFO=/lib/terminfo/' >> /home/sdbadmin/.bashrc
RUN chown -R shiyanlou:shiyanlou /home/shiyanlou


RUN apt-get -y update \
    && apt-get -y install openssh-server \
    && apt-get -y install expect \
    && apt-get -y install openjdk-8-jdk \
    && apt-get -y install fuse \
    && apt-get -y install curl \
    && apt-get -y install lsof \
    && apt-get -y install cron \
    && apt-get -y install -y libcurl4-openssl-dev


#    && apt-get -y install -y libcurl4-gnutls-dev \

RUN apt-get -y install libncurses5-dev

COPY gosu /usr/local/bin/
RUN set -ex; \
	rm -rf /var/lib/apt/lists/*; \
	chmod +x /usr/local/bin/gosu; 


# no passwd ssh login
RUN mkdir -p  /var/run/sshd \
    && sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

RUN echo 'shiyanlou    ALL=(ALL:ALL) NOPASSWD:ALL'>> /etc/sudoers
RUN echo 'sdbadmin    ALL=(ALL:ALL) NOPASSWD:ALL'>> /etc/sudoers

EXPOSE 22

ADD package.tar.gz /home/sdbadmin

RUN chown -R  sdbadmin:sdbadmin_group /home/sdbadmin/package

RUN chown sdbadmin:sdbadmin_group /opt

ADD entrypoint_sdb_install.sh /
ADD create1copy.js   /
ADD createdate1.js   /
ADD createdate2.js   /
ADD createdate3.js   /
ADD rmtmpcoord.js    /

RUN chmod 755 /entrypoint_sdb_install.sh
ENTRYPOINT ["/entrypoint_sdb_install.sh"]
